version: '3.1'

services:
  rabbitmq:
    container_name: "rabbitmq-parana-bank"  
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 
      RABBITMQ_DEFAULT_PASS: 

  mongo:
    container_name: "mongodb-parana-bank"  
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    
  mongo-express:
    container_name: "mongo-express-parana-bank"  
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 
      ME_CONFIG_BASICAUTH_PASSWORD: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_MONGODB_URL: mongodb://:@mongo:27017/
  
volumes:
  rabbitmq_data:
