version: '3.7'

services:
  rabbitmq:
    container_name: "rabbitmq-parana-bank"  
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 
      RABBITMQ_DEFAULT_PASS: 

  mongodb:
    container_name: "mongodb-parana-bank"  
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    
  mongo-express:
    container_name: "mongo-express-parana"  
    image: "mongo-express"
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_MONGODB_SERVER: mongo
      
volumes:
  rabbitmq_data:
  mongodb_data:  
     driver: local  
